### ISSUE TITLE
Modular DAL initialization

### ISSUE THREAD

**Issue by DrMondGnu** [Yggdrasil-Worlds/DAL#23]
I think there should be a way to modify the initialization for the DAL especially for testing purposes.
When the DAL initializes it always tries to load any .env file and setup a data base connection which is counterintuitive. Maybe you could change the DAL structure to initialize with a initialize method which needs to be called before any usage. This would highly increase the options for configuring a connection to any third party Service or custom implementations for data management such is in memory.

**Comment by Invincible2211** [comment]
That doesn't align with the use case of the DAL. The DAL requires specific data sources because it manages the config management. I could look into creating an initialize method that offers more configuration options, but typically, you should assume that you won't be setting up all connections afterward. The DAL will be used by numerous modules simultaneously, so ordinarily, no one should be tampering with the pre-implemented data sources (data integrity and such).

If there's only an initialize method that needs to be called once, who has the right from all modules to decide what the connection data is?

Also, changing the configuration used there isn't possible after the initial connection setup (due to ORM constraints).

The intended use case is that you simply add your required data sources to the DAL or utilize existing ones and only handle the connection for your own data sources.

Moreover, there's a specific method for testing?!? It initializes the DAL with the provided data there.

**Comment by DrMondGnu** [comment]
link pls 👉👈

**Comment by Invincible2211** [comment]
link for what? 😅

**Comment by DrMondGnu** [comment]
test method

**Comment by Invincible2211** [comment]
https://github.com/Yggdrasil-Worlds/DAL/blob/dev/src/main/java/de/yggdrasil/core/dal/DAL.java
last method
